import type { Role } from './types'

/** Newest first. The unit tests hold this order. */
export const experience: readonly Role[] = [
  {
    slug: 'streamlyne',
    company: 'Streamlyne',
    title: 'Senior Software Engineer',
    start: '2025-07',
    location: 'U.S.',
    arrangement: 'remote',
    bullets: [
      'Work on the platform U.S. universities run their research administration on, including a real-time messaging product with voice that helps researchers prepare documents, answer university policy questions, and plan budgets. Submissions went up 29%.',
      'Build and maintain product across the frontend and the backend, and take part in roadmap and technical decisions that weigh customer needs against delivery speed and what we can maintain later.',
      'Helped modernize a long-running Java application by rebuilding selected workflows in React and Node, cutting load times 44%, and put the project in Docker so other developers could run it locally.',
      'Work with product and other engineers to break down vague problems and judge whether something is a quick fix, an architectural change, or a roadmap item.',
    ],
  },
  {
    slug: 'surveva',
    company: 'Surveva',
    title: 'Senior Mobile Engineer',
    start: '2024-04',
    end: '2025-09',
    location: 'Kuwait',
    arrangement: 'remote',
    bullets: [
      'Built and maintained features for the Surveva survey app in Flutter and Node.js.',
      'Wrote a lazy-loading algorithm that cut survey load times 25%, which mattered most to people working through longer surveys.',
      'Worked across the UI, application logic, API integrations, debugging, and release prep, and helped decide the frontend architecture with a remote team.',
      'Built a CI/CD pipeline so the team could test and ship more reliably from different time zones.',
    ],
  },
  {
    slug: 'riyadh-real-estate',
    company: 'Riyadh Real Estate',
    title: 'Software Engineer',
    start: '2023-12',
    end: '2024-04',
    location: 'France',
    arrangement: 'remote',
    bullets: [
      'Built a property management platform and helped onboard more than 500 property owners.',
      'Worked across the frontend and the backend on a remote contract: API integration, debugging, and shipping features.',
    ],
  },
  {
    slug: 'newline',
    company: 'newLine',
    title: 'Frontend Developer',
    start: '2023-09',
    end: '2023-11',
    location: 'Contract',
    arrangement: 'remote',
    bullets: [
      'Led the author dashboard for publishing educational content to more than 5,000 students, building the video and book management experience in Next.js and Redux.',
      "Connected the dashboard to Discord's API so students could comment from Discord without leaving where they already were.",
      'Built reporting views on MongoDB so authors could watch how their content performed, and planned milestones with senior management.',
    ],
  },
  {
    slug: 'tintash',
    company: 'Tintash',
    title: 'Frontend Engineer',
    start: '2023-02',
    end: '2023-08',
    location: 'Contract',
    arrangement: 'remote',
    bullets: [
      'Led a subscription dashboard for premium content and newsletters, which raised subscriptions 25%.',
      'Worked with a cross-functional team on the frontend of an NFL-focused sports product and helped choose its architecture.',
      'Added end-to-end tests and release checks that caught problems before production.',
    ],
  },
  {
    slug: 'majisoft-innovations',
    company: 'MajiSoft Innovations',
    title: 'Full Stack Engineer',
    start: '2022-01',
    end: '2023-02',
    location: 'Nairobi, Kenya',
    arrangement: 'hybrid',
    bullets: [
      'Designed and built a property management platform for owners and agents.',
      'Added analytics so property managers could see where their traffic came from, which improved ad spending by up to 20%.',
      'Built the backend workflows for uploading and tracking properties and agents.',
    ],
  },
  {
    slug: 'park254',
    company: 'Park254',
    title: 'Mobile Engineer',
    start: '2021-01',
    end: '2021-12',
    location: 'Nairobi, Kenya',
    arrangement: 'remote',
    bullets: [
      'Designed and built a parking app that helped drivers find parking near them.',
      'Integrated Google Maps and routing to guide drivers to the lot they picked.',
      'Added in-app payments and the backend jobs that worked out parking time.',
    ],
  },
  {
    slug: 'softsearchlab',
    company: 'SoftsearchLab',
    title: 'Frontend Developer Intern',
    start: '2020-01',
    end: '2020-06',
    location: 'Nairobi, Kenya',
    arrangement: 'on-site',
    bullets: [
      'Built frontend screens and authentication for a logistics startup tracking truckloads and revenue.',
      'Added dynamic search and worked on performance and page loading.',
    ],
  },
]
